In [4]:
import numpy as np
import pandas as pd
from sklearn import preprocessing, ensemble

In [5]:
# columns to be used as features #
feature_cols = ["ind_empleado","pais_residencia","sexo","age", "ind_nuevo", "antiguedad", "nomprov", "segmento"]
dtype_list = {'ind_cco_fin_ult1': 'float16', 'ind_deme_fin_ult1': 'float16', 'ind_aval_fin_ult1': 'float16', 'ind_valo_fin_ult1': 'float16', 'ind_reca_fin_ult1': 'float16', 'ind_ctju_fin_ult1': 'float16', 'ind_cder_fin_ult1': 'float16', 'ind_plan_fin_ult1': 'float16', 'ind_fond_fin_ult1': 'float16', 'ind_hip_fin_ult1': 'float16', 'ind_pres_fin_ult1': 'float16', 'ind_nomina_ult1': 'float16', 'ind_cno_fin_ult1': 'float16', 'ncodpers': 'int64', 'ind_ctpp_fin_ult1': 'float16', 'ind_ahor_fin_ult1': 'float16', 'ind_dela_fin_ult1': 'float16', 'ind_ecue_fin_ult1': 'float16', 'ind_nom_pens_ult1': 'float16', 'ind_recibo_ult1': 'float16', 'ind_deco_fin_ult1': 'float16', 'ind_tjcr_fin_ult1': 'float16', 'ind_ctop_fin_ult1': 'float16', 'ind_viv_fin_ult1': 'float16', 'ind_ctma_fin_ult1': 'float16'}
target_cols = ['ind_ahor_fin_ult1','ind_aval_fin_ult1','ind_cco_fin_ult1','ind_cder_fin_ult1','ind_cno_fin_ult1','ind_ctju_fin_ult1','ind_ctma_fin_ult1','ind_ctop_fin_ult1','ind_ctpp_fin_ult1','ind_deco_fin_ult1','ind_deme_fin_ult1','ind_dela_fin_ult1','ind_ecue_fin_ult1','ind_fond_fin_ult1','ind_hip_fin_ult1','ind_plan_fin_ult1','ind_pres_fin_ult1','ind_reca_fin_ult1','ind_tjcr_fin_ult1','ind_valo_fin_ult1','ind_viv_fin_ult1','ind_nomina_ult1','ind_nom_pens_ult1','ind_recibo_ult1']

In [6]:
# train file

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_ba6234822f384127b229f60fc9ccfe27 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='MZcFtwrNsiVZN593UTiDpPTY3cGsKFznqbWtB_D8CQqS',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_ba6234822f384127b229f60fc9ccfe27.get_object(Bucket='meraki-donotdelete-pr-o7utn8mfhdu9qq',Key='Meraki_Dataset.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_1 = pd.read_csv(body)
df_data_1.head()

,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,...,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
0,28-01-2015,1375586,N,ES,H,35.0,12-01-2015,0.0,6.0,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
1,28-01-2015,1050611,N,ES,V,23.0,10-08-2012,0.0,35.0,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
2,28-01-2015,1050612,N,ES,V,23.0,10-08-2012,0.0,35.0,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
3,28-01-2015,1050613,N,ES,H,22.0,10-08-2012,0.0,35.0,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
4,28-01-2015,1050614,N,ES,V,23.0,10-08-2012,0.0,35.0,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0

In [7]:
# test file

body = client_ba6234822f384127b229f60fc9ccfe27.get_object(Bucket='meraki-donotdelete-pr-o7utn8mfhdu9qq',Key='Meraki_Test.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_2 = pd.read_csv(body)
df_data_2.head()

,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,...,indext,conyuemp,canal_entrada,indfall,tipodom,cod_prov,nomprov,ind_actividad_cliente,renta,segmento
0,28-06-2016,15889,F,ES,V,56,16-01-1995,0,256,1,...,N,N,KAT,N,1,28,MADRID,1,326124.90,01 - TOP
1,28-06-2016,1170544,N,ES,H,36,28-08-2013,0,34,1,...,N,NaN,KAT,N,1,3,ALICANTE,0,NA,02 - PARTICULARES
2,28-06-2016,1170545,N,ES,V,22,28-08-2013,0,34,1,...,N,NaN,KHE,N,1,15,"CORUÑA, A",1,NA,03 - UNIVERSITARIO
3,28-06-2016,1170547,N,ES,H,22,28-08-2013,0,34,1,...,N,NaN,KHE,N,1,8,BARCELONA,0,148402.98,03 - UNIVERSITARIO
4,28-06-2016,1170548,N,ES,H,22,28-08-2013,0,34,1,...,N,NaN,KHE,N,1,7,"BALEARS, ILLES",0,106885.80,03 - UNIVERSITARIO

In [8]:
train_size = 50000
nrows = 50000

start_index = train_size - nrows

In [9]:
for ind, col in enumerate(feature_cols):
    print(col)
    train = df_data_1
    test = df_data_2
    train.fillna(-99, inplace=True)
    test.fillna(-99, inplace=True)
    if train[col].dtype == "object":
        le = preprocessing.LabelEncoder()
        le.fit(list(train[col].values) + list(test[col].values))
        temp_train_X = le.transform(list(train[col].values)).reshape(-1,1)[start_index:,:]
        temp_test_X = le.transform(list(test[col].values)).reshape(-1,1)
    else:
        temp_train_X = np.array(train[col]).reshape(-1,1)[start_index:,:]
        temp_test_X = np.array(test[col]).reshape(-1,1)
    if ind == 0:
        train_X = temp_train_X.copy()
        test_X = temp_test_X.copy()
    else:
        train_X = np.hstack([train_X, temp_train_X])
        test_X = np.hstack([test_X, temp_test_X])
    print(train_X.shape, test_X.shape)
del train
del test

ind_empleado
(50000, 1) (500, 1)
pais_residencia
(50000, 2) (500, 2)
sexo
(50000, 3) (500, 3)
age
(50000, 4) (500, 4)
ind_nuevo
(50000, 5) (500, 5)
antiguedad
(50000, 6) (500, 6)
nomprov
(50000, 7) (500, 7)
segmento
(50000, 8) (500, 8)

In [10]:
df_data_1.to_csv('train_file.csv')
train_y = pd.read_csv(open('train_file.csv'), usecols=['ncodpers']+target_cols, dtype=dtype_list)
last_instance_df = train_y.drop_duplicates('ncodpers', keep='last')
train_y = np.array(train_y.fillna(0)).astype('int')[start_index:,1:]
print(train_X.shape, train_y.shape)
print(test_X.shape)

(50000, 8) (50000, 24)
(500, 8)

In [12]:
print("Running Model..")
model = ensemble.RandomForestClassifier(n_estimators=10, max_depth=10, min_samples_leaf=10, n_jobs=4, random_state=2016)
model.fit(train_X, train_y)
del train_X, train_y
print("Predicting..")
preds = model.predict_proba(test_X)
#preds = np.array(model.predict_proba(test_X))[:,:].T
del test_X

Running Model..
Predicting..

In [13]:
preds.shape

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
print("Getting last instance dict..")
last_instance_df = last_instance_df.fillna(0).astype('int')
cust_dict = {}
target_cols = np.array(target_cols)
for ind, row in last_instance_df.iterrows():
    cust = row['ncodpers']
    used_products = set(target_cols[np.array(row[1:])==1])
    cust_dict[cust] = used_products
del last_instance_df

In [16]:
print("Creating submission..")
preds = np.argsort(preds, axis=1)
preds = np.fliplr(preds)
test_id = np.array(pd.read_csv(test_file, usecols=['ncodpers'])['ncodpers'])
final_preds = []
for ind, pred in enumerate(preds):
    cust = test_id[ind]
    top_products = target_cols[pred]
    used_products = cust_dict.get(cust,[])
    new_top_products = []
    for product in top_products:
        if product not in used_products:
            new_top_products.append(product)
        if len(new_top_products) == 7:
            break
    final_preds.append(" ".join(new_top_products))

Creating submission..

ValueError: could not broadcast input array from shape (500,1) into shape (500)

In [ ]:
print("Getting last instance dict..")
last_instance_df = last_instance_df.fillna(0).astype('int')
cust_dict = {}
target_cols = np.array(target_cols)
for ind, row in last_instance_df.iterrows():
    cust = row['ncodpers']
    used_products = set(target_cols[np.array(row[1:])==1])
    cust_dict[cust] = used_products
del last_instance_df

In [ ]:
print("Creating submission..")
preds = np.argsort(preds, axis=1)
preds = np.fliplr(preds)
test_id = np.array(pd.read_csv(test_file, usecols=['ncodpers'])['ncodpers'])
final_preds = []
for ind, pred in enumerate(preds):
    cust = test_id[ind]
    top_products = target_cols[pred]
    used_products = cust_dict.get(cust,[])
    new_top_products = []
    for product in top_products:
        if product not in used_products:
            new_top_products.append(product)
            if len(new_top_products) == 7:
                break
            final_preds.append(" ".join(new_top_products))