In [1]:

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression
from collections import defaultdict

In [3]:

usecols = ['ncodpers', 'ind_ahor_fin_ult1', 'ind_aval_fin_ult1', 'ind_cco_fin_ult1',
       'ind_cder_fin_ult1', 'ind_cno_fin_ult1', 'ind_ctju_fin_ult1',
       'ind_ctma_fin_ult1', 'ind_ctop_fin_ult1', 'ind_ctpp_fin_ult1',
       'ind_deco_fin_ult1', 'ind_deme_fin_ult1', 'ind_dela_fin_ult1',
       'ind_ecue_fin_ult1', 'ind_fond_fin_ult1', 'ind_hip_fin_ult1',
       'ind_plan_fin_ult1', 'ind_pres_fin_ult1', 'ind_reca_fin_ult1',
       'ind_tjcr_fin_ult1', 'ind_valo_fin_ult1', 'ind_viv_fin_ult1',
       'ind_nomina_ult1', 'ind_nom_pens_ult1', 'ind_recibo_ult1']

In [5]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3


def model():

    def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_ba6234822f384127b229f60fc9ccfe27 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='MZcFtwrNsiVZN593UTiDpPTY3cGsKFznqbWtB_D8CQqS',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_ba6234822f384127b229f60fc9ccfe27.get_object(Bucket='meraki-donotdelete-pr-o7utn8mfhdu9qq',Key='Meraki_Dataset.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_1 = pd.read_csv(body)
df_data_1.head()

/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,...,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
0,28-01-2015,1375586,N,ES,H,35.0,12-01-2015,0.0,6.0,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
1,28-01-2015,1050611,N,ES,V,23.0,10-08-2012,0.0,35.0,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
2,28-01-2015,1050612,N,ES,V,23.0,10-08-2012,0.0,35.0,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
3,28-01-2015,1050613,N,ES,H,22.0,10-08-2012,0.0,35.0,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
4,28-01-2015,1050614,N,ES,V,23.0,10-08-2012,0.0,35.0,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0

In [6]:

body = client_ba6234822f384127b229f60fc9ccfe27.get_object(Bucket='meraki-donotdelete-pr-o7utn8mfhdu9qq',Key='Meraki_Test.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_2 = pd.read_csv(body)
df_data_2.head()

,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,...,indext,conyuemp,canal_entrada,indfall,tipodom,cod_prov,nomprov,ind_actividad_cliente,renta,segmento
0,28-06-2016,15889,F,ES,V,56,16-01-1995,0,256,1,...,N,N,KAT,N,1,28,MADRID,1,326124.90,01 - TOP
1,28-06-2016,1170544,N,ES,H,36,28-08-2013,0,34,1,...,N,NaN,KAT,N,1,3,ALICANTE,0,NA,02 - PARTICULARES
2,28-06-2016,1170545,N,ES,V,22,28-08-2013,0,34,1,...,N,NaN,KHE,N,1,15,"CORUÑA, A",1,NA,03 - UNIVERSITARIO
3,28-06-2016,1170547,N,ES,H,22,28-08-2013,0,34,1,...,N,NaN,KHE,N,1,8,BARCELONA,0,148402.98,03 - UNIVERSITARIO
4,28-06-2016,1170548,N,ES,H,22,28-08-2013,0,34,1,...,N,NaN,KHE,N,1,7,"BALEARS, ILLES",0,106885.80,03 - UNIVERSITARIO

In [7]:
df_data_1[usecols]

,ncodpers,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,ind_ctju_fin_ult1,ind_ctma_fin_ult1,ind_ctop_fin_ult1,ind_ctpp_fin_ult1,...,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
0,1375586,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
1,1050611,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
2,1050612,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
3,1050613,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
4,1050614,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
5,1050615,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
6,1050616,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
7,1050617,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
8,1050619,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
9,1050620,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
10,1050621,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
11,1050622,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
12,1050623,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
13,1050624,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
14,1050625,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
15,1050626,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
16,1050610,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
17,1050627,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
18,1050609,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
19,1050605,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
20,1050582,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
21,1050586,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,1
22,1050588,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
23,1050589,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
24,1050591,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
25,1050592,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
26,1050595,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
27,1050596,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
28,1050597,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
29,1050598,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,1124574,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49971,1124577,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49972,1124584,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0.0,0.0,1
49973,1124585,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0.0,0.0,1
49974,1124586,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49975,1124587,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49976,1124590,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49977,1124592,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,1
49978,1124593,0,0,0,0,1,0,0,0,0,...,0,0,0,1,1,0,0,1.0,1.0,1
49979,1124594,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49980,1124595,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,1,0,1.0,1.0,1
49981,1124597,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0.0,0.0,0
49982,1124600,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49983,1124605,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49984,1124606,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49985,1124573,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49986,1124526,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49987,1124571,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49988,1124568,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49989,1124531,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49990,1124533,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49991,1124537,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49992,1124541,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1.0,1.0,1
49993,1124542,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49994,1124546,0,0,1,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0.0,0.0,1
49995,1124548,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49996,1124549,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0.0,0.0,1
49997,1124550,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49998,1124551,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
49999,1124552,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0

In [8]:
body = client_ba6234822f384127b229f60fc9ccfe27.get_object(Bucket='meraki-donotdelete-pr-o7utn8mfhdu9qq',Key='sample_submission.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_3 = pd.read_csv(body)
df_data_3.head()

   ncodpers     added_products
0     15889  ind_tjcr_fin_ult1
1     15890  ind_tjcr_fin_ult1
2     15892  ind_tjcr_fin_ult1
3     15893  ind_tjcr_fin_ult1
4     15894  ind_tjcr_fin_ult1

In [9]:
def model():
    df_train = df_data_1[usecols]
    sample = df_data_3
    df_train = df_train.drop_duplicates(['ncodpers'], keep='last')
    df_train.fillna(0, inplace=True)

    models = {}
    model_preds = {}
    id_preds = defaultdict(list)
    ids = df_train['ncodpers'].values
    for c in df_train.columns:
        if c != 'ncodpers':
            print(c)
            y_train = df_train[c]
            x_train = df_train.drop([c, 'ncodpers'], 1)

            clf = LogisticRegression()
            clf.fit(x_train, y_train)
            p_train = clf.predict_proba(x_train)[:,1]

            models[c] = clf
            model_preds[c] = p_train
            for id, p in zip(ids, p_train):
                id_preds[id].append(p)

            print(roc_auc_score(y_train, p_train))

    already_active = {}
    for row in df_train.values:
        row = list(row)
        id = row.pop(0)
        active = [c[0] for c in zip(df_train.columns[1:], row) if c[1] > 0]
        already_active[id] = active

    train_preds = {}
    for id, p in id_preds.items():
        preds = [i[0] for i in sorted([i for i in zip(df_train.columns[1:], p) if i[0] not in already_active[id]], key=lambda i:i [1], reverse=True)[:7]]
        train_preds[id] = preds

    test_preds = []
    for row in sample.values:
        id = row[0]
        p = train_preds[id]
        test_preds.append(' '.join(p))

    sample['added_products'] = test_preds
    sample.to_csv('collab_sub.csv', index=False)
    return sample

In [10]:
if __name__ == "__main__":
    model()

ind_ahor_fin_ult1

/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 0